# Generated by Django 3.0.3 on 2020-10-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('char_app', '0020_auto_20200523_1048'),
        ('campaigns_diary', '0006_auto_20200503_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('characters', models.ManyToManyField(null=True, to='char_app.Character')),
                ('which_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns_diary.Campaign')),
            ],
        ),
    ]
