# Generated by Django 3.0.3 on 2020-10-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0020_auto_20200523_1048'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='characters',
            field=models.ManyToManyField(blank=True, to='char_app.Character'),
        ),
    ]
