# Generated by Django 3.0.3 on 2020-10-11 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20201010_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('which_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.Quest')),
            ],
        ),
    ]
