# Generated by Django 3.0.3 on 2020-02-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('basic_class', models.CharField(max_length=32)),
                ('additional_class', models.CharField(max_length=32)),
                ('basic_level', models.IntegerField()),
                ('additional_level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('race', models.CharField(max_length=32)),
                ('alignment', models.IntegerField()),
                ('background', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_app.Player')),
            ],
        ),
    ]
