# Generated by Django 3.0.3 on 2020-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='additional_class',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='additional_level',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(default='TBD', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
