# Generated by Django 3.0.3 on 2020-02-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0002_auto_20200222_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('realm', models.CharField(default='Forgotten Realms', max_length=64)),
                ('characters', models.ManyToManyField(to='char_app.Character')),
            ],
        ),
    ]
