# Generated by Django 3.0.3 on 2020-04-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0004_auto_20200308_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
