# Generated by Django 3.0.3 on 2020-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0008_auto_20200517_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='additional_class',
        ),
        migrations.AddField(
            model_name='character',
            name='additional_class',
            field=models.ManyToManyField(related_name='additional_class', to='char_app.Classes'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.ManyToManyField(to='char_app.Alignments'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='basic_class',
        ),
        migrations.AddField(
            model_name='character',
            name='basic_class',
            field=models.ManyToManyField(related_name='basic_class', to='char_app.Classes'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ManyToManyField(to='char_app.Races'),
        ),
    ]
