# Generated by Django 3.0.3 on 2020-05-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0009_auto_20200517_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='additional_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='basic_class',
        ),
        migrations.AddField(
            model_name='character',
            name='hero_classes',
            field=models.ManyToManyField(related_name='classes', to='char_app.Classes'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='char_app.Alignments'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='char_app.Races'),
        ),
    ]
