# Generated by Django 3.0.3 on 2020-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0012_auto_20200522_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom_save_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom_save_prof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='hero_classes',
            field=models.ManyToManyField(to='char_app.Classes'),
        ),
    ]
