# Generated by Django 3.0.3 on 2020-05-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0013_auto_20200522_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='acrobatics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='animal_handling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='arcana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='athletics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='deception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='insight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intimidation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='investigation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='medicine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='nature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='passive_perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='persuasion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='religion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='sleigh_of_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='stealth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='survival',
            field=models.IntegerField(default=0),
        ),
    ]
