# Generated by Django 3.0.3 on 2020-05-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0016_auto_20200523_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sleigh_of_hand_prof',
            new_name='sleight_of_hand_prof',
        ),
    ]
