# Generated by Django 3.0.3 on 2020-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0017_auto_20200523_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='passive_perception',
            field=models.IntegerField(default=0),
        ),
    ]
