# Generated by Django 3.0.3 on 2020-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0018_auto_20200523_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.DecimalField(decimal_places=1, default=9, max_digits=3),
        ),
    ]
