# Generated by Django 3.0.3 on 2020-05-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0019_auto_20200523_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charisma_save_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution_save_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity_save_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence_save_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength_save_mod',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom_save_mod',
        ),
    ]
