# Generated by Django 3.0.3 on 2020-04-12 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('char_app', '0005_delete_campaign'),
        ('campaigns_diary', '0002_auto_20200412_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(to='char_app.Character'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(to='char_app.Player'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='realm',
            field=models.CharField(default='Forgotten Realms', max_length=64),
        ),
    ]
