# Generated by Django 3.0.3 on 2020-04-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns_diary', '0003_auto_20200412_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='comment',
            new_name='description',
        ),
    ]
